apiVersion: apps/v1
kind: Deployment
metadata:
  name: revhire-job
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: revhire-job
  template:
    metadata:
      labels:
        app : revhire-job
    spec:
      containers:
        - name: revhire-job
          image: public.ecr.aws/a6p3b4m6/revhire-job-service:latest

---
apiVersion: v1
kind: Service
metadata:
  name: revhire-job-service
  labels:
    app: revhire-job
spec:
  selector:
    app: revhire-job
  ports:
    - protocol: 'TCP'
      port: 8000
      targetPort: 8000
  type: ClusterIP